vim.loader.enable()
require "placeholder.keymaps"
require "placeholder.options"
require "placeholder.plugins.lsp"
require "placeholder.plugins.lualine"
require "placeholder.plugins.cmp"
require "placeholder.plugins.gitsigns"
require "placeholder.plugins.nvim-tree"
require "placeholder.plugins.harpoon"
require "placeholder.plugins.treesitter"
require "placeholder.plugins.trouble"
require "placeholder.plugins.theme"
require "placeholder.plugins.fzf-lua"
require "placeholder.plugins.dap"
